### ISSUE TITLE
IOError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by arielb2** [fedora-infra/pkgwat.cli#35]
I try to run the following:

]$ git clone https://github.com/fedora-infra/pkgwat.cli.git

]$ cd pkgwat.cli
]$ sudo python setup.py build
]$ sudo python setup.py install

```
$ pkgwat search pkgwat
Traceback (most recent call last):
  File "/bin/pkgwat", line 9, in <module>
    load_entry_point('pkgwat.cli==0.11', 'console_scripts', 'pkgwat')()
  File "/usr/lib/python2.7/site-packages/pkgwat.cli-0.11-py2.7.egg/pkgwat/cli/main.py", line 62, in main
    myapp = PkgWat()
  File "/usr/lib/python2.7/site-packages/pkgwat.cli-0.11-py2.7.egg/pkgwat/cli/main.py", line 26, in __init__
    manager = cliff.commandmanager.CommandManager('pkgwat.subcommands')
  File "/usr/lib/python2.7/site-packages/cliff-2.1.0-py2.7.egg/cliff/commandmanager.py", line 38, in __init__
    self._load_commands()
  File "/usr/lib/python2.7/site-packages/cliff-2.1.0-py2.7.egg/cliff/commandmanager.py", line 42, in _load_commands
    self.load_commands(self.namespace)
  File "/usr/lib/python2.7/site-packages/cliff-2.1.0-py2.7.egg/cliff/commandmanager.py", line 46, in load_commands
    for ep in pkg_resources.iter_entry_points(namespace):
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 711, in iter_entry_points
    entries = dist.get_entry_map(group)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2728, in get_entry_map
    self._get_metadata('entry_points.txt'), self
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2458, in parse_map
    for group, lines in data:
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3092, in split_sections
    for line in yield_lines(s):
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2313, in yield_lines
    for ss in strs:
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2654, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1623, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1615, in get_metadata
    return self._get(self._fn(self.egg_info, name))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1726, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/fabulous-0.3.0-py2.7.egg/EGG-INFO/entry_points.txt'
```

**Comment by pypingou** [comment]
If you're running Fedora, did you try installing the RPM?

**Comment by arielb2** [comment]
yes, I am running fedora, this works with rpm

**Comment by pypingou** [comment]
So I would close this as notabug, there is apparently something that went wrong on your system on how it installed the `fabulous` module, but I'm not sure there is much we can do about it

**Comment by arielb2** [comment]
apparently to install manually download the version 0.3 of fabulous, and using rpm, install the version fabulous-0.2.0

thanks your comments.

**Comment by pypingou** [comment]
There is likely something odd w/ fabulous but there isn't much we can do for this on our side

Thanks for your report :)
